// packages/server/scripts/build.mjs
// esbuild bundle script — compiles the DevBridge server into a single CJS file.
// Output: dist/server.cjs  (used by pkg to build the exe)

import { build } from 'esbuild';
import path from 'node:path';
import url from 'node:url';
import fs from 'node:fs';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root      = path.resolve(__dirname, '..');
const outDir    = path.join(root, 'dist');

// Ensure output directory exists
fs.mkdirSync(outDir, { recursive: true });

// Native modules that MUST remain as external requires (they contain .node binaries)
const nativeExternals = [
  'node-hid',
  'serialport',
  '@serialport/bindings-cpp',
  '@abandonware/noble',
  'usb',
  'node-ffi-napi',
  'ref-napi',
];

// Pino transport modules loaded dynamically — keep external
// Note: thread-stream is bundled (NOT external) because pino/lib/transport.js
// requires it at module-load time even when no transport is configured.
// pino-pretty and pino/file are still external (only used in CLI/dev mode).
const dynamicExternals = [
  'pino-pretty',
  'pino/file',
];

// esbuild itself is used by PluginLoader at runtime — keep external
const toolExternals = [
  'esbuild',
  '@esbuild/win32-x64',
  '@esbuild/linux-x64',
  '@esbuild/darwin-arm64',
];

await build({
  entryPoints: [path.join(root, 'src', 'index.ts')],
  bundle:      true,
  platform:    'node',
  target:      'node20',
  format:      'cjs',
  outfile:     path.join(outDir, 'server.cjs'),
  sourcemap:   true,
  minify:      false,           // keep readable for beta debugging
  treeShaking: true,

  // Resolve workspace package by path (since pnpm links them)
  alias: {
    '@devbridge/shared': path.resolve(root, '..', 'shared', 'src', 'index.ts'),
  },

  external: [
    ...nativeExternals,
    ...dynamicExternals,
    ...toolExternals,
    // Node.js built-ins are automatically externalised by esbuild with platform:node
  ],

  // Banner: mark this as a CJS bundle
  banner: {
    js: '// DevBridge Server Bundle — generated by esbuild\n',
  },

  // Silence noisy warnings for optional native deps
  logLevel: 'info',

  plugins: [
    {
      name: 'optional-native-warn',
      setup(build) {
        build.onResolve({ filter: /^(node-hid|serialport|noble|usb|ffi|ref-napi)/ }, args => {
          return { path: args.path, external: true };
        });
      },
    },
  ],
});

console.log('[build] ✓ server.cjs written to', outDir);
